server:
  port: 9002
spring:
  application:
    name: card-holder-app

  cloud:
    openfeign:
      client:
        config:
          creditAnalysisClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
            dismiss404: true

  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect